call build keyword 1 001 "Arrival at dawn in Frankfurt Airport"
call build keyword 2 005 "The Cathedral of Cologne, main door"
call build keyword 2 006 "Bell in Bell tower inside the Cathedral of Cologne"
call build keyword 2 007 "Gothic spires of the Cathedral of Cologne"
call build keyword 1 008 "Inside a spire at the Cathedral of Cologne"
call build keyword 1 009 "Inside the Cathedral of Cologne"
call build keyword 1 012 "View of Cologne from across the river"
call build keyword 1 016 "Evoke Demo Party"
call build keyword 1 017 "3D glasses watching 3D demos at Evoke Demo Party"
call build keyword 1 018 "Demo show at the Evoke Demo Party"
call build keyword 1 025 "Sculpture of Beethoven"
call build keyword 2 027 "Cog train up to the Ruins Dachenfels"
call build keyword 3 029 "View of Bonn and way back there Cologne from Konigswinter on the Rhine"
call build keyword 1 031 "Ruins Dachenfels at Konigswinter on the Rhine"
call build keyword 3 032 "Castle at Konigswinter on the Rhine"
call build keyword 1 033 "Old cog train at Konigswinter on the Rhine"
call build keyword 1 034 "Deutsches Eck, monument where the Mosel and Rhine rivers join"
call build keyword 1 035 "Deutsches Eck, monument where the Mosel and Rhine rivers join"
call build keyword 1 037 "Erhenbreitstein fortress at Koblenz"
call build keyword 1 038 "Castle on the Rhine"
call build keyword 3 040 "City on the Rhine"
call build keyword 1 044 "The Loreley on the Rhine"
call build keyword 1 045 "The siren of Loreley watches down from the high cliffs of the Rhine"
call build keyword 1 054 "Vince in Burg Rheinfels, ruins of vaults"
call build keyword 1 055 "entering inside Burg Rheinfels"
call build keyword 1 056 "Small tunnels are below the castle, the camera flash is brief"
call build keyword 1 057 "I use my blinky blue light to see"
call build keyword 1 058 "Another castle over a Rhine river city, such a treasure"
call build keyword 1 065 "I stay the night in Bingin, and find another fall festival"
call build keyword 1 067 "Nighttime shots, after a few beers"
call build keyword 1 068 "A train rushes by"
call build keyword 1 069 "Such is the drunken state of a man alone in a fabulous place. A moment's emotion forever treasured and yet not sharable"
call build keyword 1 071 "The castle atop the hill in the city of Bingin"
call build keyword 1 072 "Me, my beer, and the crushing of flowers"
call build keyword 1 073 "After the late night, I woke up early to see the sun rise over Bingin and the Rhine"
call build keyword 1 075 "Out over the river, the castles and the vineyards"
call build keyword 1 077 "I hike a long distance from the train station to Burg Rheinstein"
call build keyword 2 078 "Rheinstein is a castle still intact, furnished, and is in contrast to most of the ruins on the Rhine"
call build keyword 1 079 "The vineyards there make use of a small trolley to navigate the hill, how fun!"
call build keyword 1 080 "Full suits of armor, and much bric-a-brac in the castle"
call build keyword 1 081 "Wooden spiral staircase, a photo must-have"
call build keyword 1 082 "The view from this castle is spectacular. The last owner, before private purchase, was a Duchess of Mecklenburg"
call build keyword 1 083 "Rheinstein's walled garden is lush, the vineyards are just beyond."
call build keyword 1 085 "I quickly travel to Mainz, a modern city in Germany. I trek in full gear. I move with focused intensity, never missing a good snapshot. Where is waldo in this picture?"
call build keyword 1 087 "The red sandstone cathedral in Mainz is a fresh contrast to most European architecture."
call build keyword 1 090 "I arrive at the Eurographics conference. We play foosball -- at full scale."
call build keyword 1 093 "The conference reception is in the Völklingen Ironworks, Saarbruecken. Here is a great flywheel."
call build keyword 1 094 "The machinery is from another age. This Demag, It inspires. "
call build keyword 1 095 "Another view of the machinery in the Völklingen Ironworks."
call build keyword 1 096 "Outside, rust covered pipes, the Völklingen Ironworks."
call build keyword 1 097 "Art in rusted pipes, the Völklingen Ironworks."
call build keyword 1 099 "The red bricks, the red rust, the Völklingen Ironworks."
call build keyword 1 102 "Vince wears a hard hat. These pipes are angled to avoid coal dust settling and accumulating"
call build keyword 1 105 "Eurographics 2002 reception dinner at the Völklingen Ironworks."
call build keyword 1 106 "Creative lighting on the flywheel"
call build keyword 1 107 "Creative lighting with creative photography with machinery"
call build keyword 1 108 "And now, Marco! In his home in Pisa!"
call build keyword 1 109 "Pisa is a beautiful Tuscan city, with much to see! And I have a first rate tour from a local."
call build keyword 1 110 "We even visit the leaning tower of Pisa"
call build keyword 1 111 "Watch out Marco! It may fall someday!"
call build keyword 2 112 "Baptismal building or something something in Pisa. "
call build keyword 1 113 "Time for food. Letizia has brought good things from Sicily. Some goat cheese, some bovine."
call build keyword 2 115 "We ride bikes, are you handling the camera safely Marco?"
call build keyword 1 117 "I lean out of a residential window in Pisa. Behind me is a butterfly, so beautiful"
call build keyword 3 118 "Pisa, crossing back to the inner city"
call build keyword 1 119 "We travel to the Tuscan mountains. Ponte della Maddelena (or Ponte del Diavolo (Devil's bridge))"
call build keyword 1 120 "Marco!"
call build keyword 1 122 "We also cross the cable suspension bridge, it is narrow. "
call build keyword 1 124 "The steps, slick under wooded shade, dead trees help your hand"
call build keyword 1 125 "A festival in San Marcello Pistoiese"
call build keyword 1 126 "Ah, with a good breakfast in the mountains."
call build keyword 1 127 "On the way back, we see the old walls of Lucca"
call build keyword 1 130 "Can you see the trees on the tower?"
call build keyword 2 136 "Cathedral in Florence"
call build keyword 1 137 "The river with no fish, and a bridge across it all built up."
call build keyword 3 140 "I remembered visiting the boboli gardens in Florence when I was young, so I returned."
call build keyword 1 142 "A statue of a naked man playing golf, plus other mostly naked humans, in the boboli gardens."
call build keyword 1 144 "More of the crowds of Florence. My day trip was not what I hoped, I was blocked by the people. I did not see David."
call build keyword 1 146 "Marco and I went to hear some electronic music. The DJ is red."
call build keyword 1 149 "I am returning home via Frankfurt. I tour museums all day."
call build keyword 1 150 "and head to the old town for my last German meal. Spatzels and beer of course!"
call build keyword 1 151 "Frankfurt at night."
call build keyword 2 153 "Airplane home. Dream of flying. Dream of dying. For what is life but sweet death delayed. I have enjoyed it."