call build keyword 1 000    "Arrival in Saarbrucken train station"
call build keyword 1 001    "Without food for the three day weekend, I fast and take hikes in the surrounding woods"
call build keyword 1 002    "The MPI where I am researching is on a university campus surrounded by wooded hills"
call build keyword 1 003    "The old bridge in downtown Saarbruecken"
call build keyword 2 010    "A new friend, Marco Tarini, apears in the rondel (a building within the MPI building)"
call build keyword 1 011    "We are many international researchers"
call build keyword 1 012    "Hitoshi, Won-Ki, Andrzej, Kiril, Vince, Marco"
call build keyword 1 013    "We play beach volleyball"
call build keyword 1 014    "We have BBQs"
call build keyword 2 015    "Marco thinks"
call build keyword 2 016    "Hitoshi works"
call build keyword 1 017    "Marco and Vince collaborate with computing devices (TI-85)"
call build keyword 1 018    "Vince sits at his office desk"
call build keyword 1 019    "We eat lunch at the Mensa, there is a nice view"
call build keyword 1 020    "Along the Mosel river is the city and castle of Cochem"
call build keyword 1 021    "Wine grapes growing on the hill up to the castle"
call build keyword 2 022    "Vince in travel gear at the castle gate"
call build keyword 1 023    "The view from the castle"
call build keyword 1 024    "Luxembourg"
call build keyword 3 025pan "Panorama of Luxemburg old city wall UNESCO walk."
call build keyword 1 028    "Detail of old casemates and fortifications of Luxembourg"
call build keyword 2 029    "Wall and bridges in Luxembourg"
call build keyword 2 030    "Stairs inside the casemates, the fortifications carved into the hill"
call build keyword 3 031pan "Inside panorama of the cathedral in Metz"
call build keyword 2 035    "Stained glass windows of the cathedral in Metz"
call build keyword 1 036    "Flying buttresses of the cathedral in Metz"
call build keyword 1 037    "The cathedral of Metz towering over nearby buildings"
call build keyword 2 038    "Naked blue chick"
call build keyword 3 039    "Grafiti in Saarbruecken. Note the two avatars and the radial design"
call build keyword 1 040    "Marc Scheib"
call build keyword 1 042    "Völklingen Ironworks, Saarbruecken. What are these I wonder, I've just seen them from the train. "
call build keyword 1 042mod "Styalized, Völklingen Ironworks, Saarbruecken"
call build keyword 1 044    "Völklingen Ironworks, Saarbruecken, I'll visit them one year later."
call build keyword 1 045    "Port Niagra, Trier, a roman city gate in the oldest city of Germany"
call build keyword 1 046    "Roman ruins in Trier"
call build keyword 1 047    "View of Trier from the wine hills"
call build keyword 1 048    "Völklingen Ironworks, Saarbruecken"
call build keyword 1 051    "View from an ICE train in Germany"
call build keyword 1 052    "View of the Mountains on the way to Fussen"
call build keyword 1 053    "Castle Neuschwanstein"
call build keyword 1 054    "My feets in the rather cold mountain stream near Castle Neuschwanstein"
call build keyword 2 055    "Castle Neuschwanstein in a very portrait sort of way"
call build keyword 3 056pan "Panorama from the environs of Castle Neuschwanstein"
call build keyword 1 058    "A not so well composed picture of me and Castle Neuschwanstein"
call build keyword 2 059    "Some very white church interior in Munich"
call build keyword 2 060    "Balls of steel in Munich. These were pretty hot from the sun.. "
call build keyword 1 061    "Me and a liter of beer in Munich. Why do I look that way?"
call build keyword 1 062    "Graffiti in Copenhaggen"
call build keyword 1 063    "Copenhagen at night, after visiting Christiania"
call build keyword 2 064    "A ship in dock in Stockholm"
call build keyword 2 065    "View from my bed on a boat in Stockholm"
call build keyword 1 066    "View of the city tower and old city of Stockholm"
call build keyword 1 068    "The gold room in the city hall of Stockholm"
call build keyword 2 069    "Detail of the USA mosaic"
call build keyword 1 070    "From the city tower in Stockholm"
call build keyword 1 071    "Please do not drive into the water"
call build keyword 1 072    "Setting up the computers at the Assembly 2001 demo party in Helsinki"
call build keyword 1 073    "The computers at the Assembly 2001 demo party in Helsinki"
call build keyword 1 074    "Downtown Helsinki"
call build keyword 2 075    "Downtown Helsinki"
call build keyword 2 076    "Giving the award for first place 64KB intro to Steven of 3State. I represented them at the Assembly Party."
call build keyword 1 078    "Train station of Amsterdam"
call build keyword 2 079    "Biking out in the countryside around Amsterdam, oh look, a windmill"
call build keyword 1 080    "Heineken brewery. End of another great trip."
